package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

// gen-openapi is the source of truth for the OpenAPI spec — it builds
// the full API graph in-process and serializes it. These tests are the
// safety net that the spec doesn't silently regress: if a path drops
// out of the registration list (or a new path is added without coverage
// elsewhere), this test catches it before the spec ships.
//
// The actual on-disk yaml is regenerated by `make gen:openapi`; this
// test verifies the *generation logic*, not the artifact.

func TestGenerateSpec_ProducesNonEmptyYAML(t *testing.T) {
	t.Parallel()

	out, err := generateSpec()

	require.NoError(t, err)
	require.NotEmpty(t, out, "generated spec must not be empty")
	assert.Contains(t, string(out), "openapi:",
		"YAML output must contain the OpenAPI version key")
	assert.Contains(t, string(out), "paths:",
		"YAML output must contain the paths block")
}

func TestGenerateSpec_AllExpectedPathsPresent(t *testing.T) {
	t.Parallel()

	out, err := generateSpec()
	require.NoError(t, err)

	var spec struct {
		Paths map[string]any `yaml:"paths"`
	}
	require.NoError(t, yaml.Unmarshal(out, &spec))

	// All Huma-registered routes. If you add or remove a path, update
	// this list. This is intentional — making it explicit forces a
	// review when the public surface changes.
	expected := []string{
		"/api/landing",
		"/api/me",
		"/api/admin/ping",
		"/api/auth/magic-link",
		"/api/auth/refresh",
		"/api/auth/logout",
		"/api/auth/logout-all",
		"/api/auth/mobile/google",
		"/api/auth/mobile/verify",
	}

	for _, path := range expected {
		assert.Contains(t, spec.Paths, path,
			"spec is missing expected path %q", path)
	}
	assert.Len(t, spec.Paths, len(expected),
		"unexpected number of paths in spec — add or remove from the expected list "+
			"in this test when the public API surface changes")
}

func TestGenerateSpec_IsValidOpenAPI31(t *testing.T) {
	t.Parallel()

	out, err := generateSpec()
	require.NoError(t, err)

	var spec struct {
		OpenAPI string         `yaml:"openapi"`
		Info    map[string]any `yaml:"info"`
		Paths   map[string]any `yaml:"paths"`
	}
	require.NoError(t, yaml.Unmarshal(out, &spec))

	assert.Contains(t, spec.OpenAPI, "3.1",
		"spec must be OpenAPI 3.1 (got %q)", spec.OpenAPI)
	assert.NotEmpty(t, spec.Info, "info block must be populated")
	assert.NotEmpty(t, spec.Paths, "paths block must be populated")
}
