import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import vitestPlugin from "@vitest/eslint-plugin";
import testingLibraryPlugin from "eslint-plugin-testing-library";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Test-only rules: vitest assertion + testing-library DOM-query hygiene.
    // Scoped to __tests__ so production code doesn't pull in test-only globals.
    files: ["src/__tests__/**/*.{ts,tsx}"],
    plugins: {
      vitest: vitestPlugin,
      "testing-library": testingLibraryPlugin,
    },
    rules: {
      ...vitestPlugin.configs.recommended.rules,
      ...testingLibraryPlugin.configs["flat/react"].rules,
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Coverage report HTML/JS — generated by vitest, not source.
    "coverage/**",
  ]),
]);

export default eslintConfig;
